// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TriviaBiblicoUNAD.Server.Datos;

#nullable disable

namespace TriviaBiblicoUNAD.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231029133812_EstudianteAddEsBorrado")]
    partial class EstudianteAddEsBorrado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TriviaBiblicoUNAD.Server.Modelos.Estudiantes.EstudianteModelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Carrera")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("EstaBorrado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechNac")
                        .HasColumnType("datetime2");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.ToTable("Estudiantes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellidos = "Perez Campusano",
                            Carrera = "Ing de Softeware",
                            EstaBorrado = false,
                            FechNac = new DateTime(2000, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = "20230024",
                            Nombre = "Jose"
                        },
                        new
                        {
                            Id = 2,
                            Apellidos = "Mendez Gonzalez",
                            Carrera = "Ing de Softeware",
                            EstaBorrado = false,
                            FechNac = new DateTime(2003, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = "20230125",
                            Nombre = "Jennifer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
